config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :employees
    
  root 'welcome#index'

  resources :companies
  resources :employees
  resources :profiles
  resources :software
  

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :employees
	has_many :profiles
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates :name, presence: true
  	validates :surname, presence: true  

	belongs_to :company
	has_one :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :company
	has_many :employees
	has_and_belongs_to_many :softwares
end

app/models/software.rb
class Software < ActiveRecord::Base
	has_and_belongs_to_many :profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?
	
	protected

	def configure_permitted_parameters
    	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:surname, :email, :password) }
  	end

  	def after_sign_in_path_for(employee)
  		employees_path
  	end

  	def after_sign_out_path_for(employee)
  		root_path
  	end

	def index
	end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :authenticate_employee!

	def new
	end

	def edit
	end

	def delete
	end

	def index
	end

	def welcome
	end

	def user_params
    	params.require(:employee).permit(:name, :surname, :email, :password, :password_confirmation, :remember_me)
  	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def new
	end

	def edit
	end

	def delete
	end
end

app/controllers/software_controller.rb
class SoftwareController < ApplicationController
	def new
	end

	def edit
	end

	def delete
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>softInstaller</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="styleeshet" href="images/favicon.ico">
	<link rel="stylesheet" href="/assets/bootstrap.css">
	<link rel="stylesheet" href="/assets/all.css">
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700|Source+Sans+Pro:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="wrapper">

	<%= render 'layouts/header' %>

	<section class="visual">
		<div class="container">
			<div class="text-block">
				<div class="heading-holder">
					<h1>softInstaller</h1>
				</div>
				<p class="tagline">Make your software installation process easier!</p>
			</div>
		</div>
		<img src="images/image_server.jpg" alt="" class="bg-stretch bg-img">
	</section>

	<section class="area">
		<div class="container">
			<div class="row">
				<div class="col-md-6">

					<ul class="visual-list">
						<li>
							<div class="img-holder">
								<img src="images/graph-01.svg" height="71" alt="">
							</div>
							<div class="text-holder">
								<h3>Designed to save your time</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
						<li>
							<div class="img-holder">
								<img src="images/graph-04.svg" width="110" alt="">
							</div>
							<div class="text-holder">
								<h3>Easy to use</h3>
								<p>Aenean cursus imperdiet nisl id fermentum. Aliquam pharetra dui laoreet vulputate dignissim. Sed id metus id quam auctor molestie eget ut augue. </p>
							</div>
						</li>
					</ul>
				</div>

				<div class="col-md-6">
					<ul class="visual-list">
						<li>
							<div class="img-holder">
								<img class="pull-left" src="images/graph-03.svg" width="90" alt="">
							</div>
							<div class="text-holder">
								<h3>High processing speed</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
						<li>
							<div class="img-holder">
								<img src="images/graph-02.svg" height="84" alt="">
							</div>
							<div class="text-holder">
								<h3>Experimental Features</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>

	<section class="area-socials">
		<div class="visual-area">
			<div class="container">
				<h2>Our socials</h2>
				<ul class="cta-list">
					<li>
						<a href="#" class="btn btn-info"><i class="fa fa-twitter"></i> Twitter</a>
					</li>
					<li>
						<a href="#" class="btn btn-blue"><i class="fa fa-facebook"></i> Facebook</a>
					</li>
				</ul>	
			</div>
		</div>
	</section>

	<section class="visual-container">
		<div class="visual-area">
			<div class="container">
				<h2>Subscription Pricing</h2>
				<div class="pricing-tables">

					<div class="plan">
		                <div class="head">
		                    <h3>Free</h3>
		                </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>0</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                <ul class="item-list">
		                    <li>30 GB Storage </li>
		                </ul>
		                <button type="button" class="btn btn-default rounded">purchase</button>
		            </div>

		            <div class="plan">
		                <div class="head">
		                    <h3>professional</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>4.99</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                    <ul class="item-list">
		                       <li>100 GB Storage</li>
		                       <li>Email Support</li>
		                    </ul>
		                <button type="button" class="btn btn-default rounded">purchase</button>
		            </div>
		            <div class="plan recommended">
		                <div class="head">
		                    <h3>agency</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>1000</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                    <ul class="item-list">
		                        <li>1 TB Storage</li>
		                        <li>Free hugs</li>
		                    </ul>
		                <button type="button" class="btn btn-default rounded">purchase</button>
		            </div>
		            <div class="plan">
		                <div class="head">
		                    <h3>company</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>79</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                <ul class="item-list">
		                    <li>Unlimited Storage</li>
		                    <li>Free pizza</li>
		                </ul>
		                <button type="button" class="btn btn-default rounded">purchase</button>
		            </div>
				</div>
			</div>
			<img src="../images/img-decor-01.jpg" height="1175" width="1380" alt="" class="bg-stretch bg-img">
		</div>
	</section>
	<section class="area">
		<div class="container">
			<div class="subscribe">
				<h3>Subscribe to Our Mail Delivery</h3>
				<form class="form-inline">
					<button type="submit" class="btn btn-primary rounded">Subscribe</button>
					<div class="form-group">
						<input type="email" class="form-control rounded" id="exampleInputEmail2" placeholder="Email...">
					</div>
				</form>
			</div>
		</div>
	</section>
	<section class="main">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="col-md-6">
						<h3>New in Release</h3>
						<h4>Cross-browser compatibility</h4>
						<p>Morbi faucibus ante ipsum, a tincidunt libero posuere et. Etiam tempor tortor at odio condimentum, sit amet fringilla ligula maximus. Mauris venenatis nisl nisi, et dictum dui aliquet nec. Sed erat, nec aliquam vel, aliquam ac felis. </p>
						<h4>Mail delivery service </h4>
						<p>Nulla purus quam, pulvinar sed ante et, feugiat maximus velit. Donec eu elit mauris. </p>
						<h4>New Design</h4>
						<p>Proin id ligula eget massa tincidunt molestie. Morbi urna lectus, molestie vel quam vel, iaculis fermentum nunc. Morbi imperdiet, leo in interdum pretium.</p>
						<div class="btn-holder">
							<a href="#" class="btn btn-link">Go to Release Log</a>
						</div>
					</div>
					<div class="col-md-6">
						<h3>New From the Blog</h3>
						<h4><a href="#">Morbi imperdiet, leo in interdum pretium.</a></h4>
						<time class="date" datetime="2015-02-18">February 18, 2015</time>
						<h4><a href="#">Donec orci ante, porta vel nulla quis, aliquet hendrerit leo.</a></h4>
						<time class="date" datetime="2015-02-12">February 12, 2015</time>
						<h4><a href="#">Suspendisse egestas vulputate luctus.</a></h4>
						<time class="date" datetime="2015-02-06">February 6, 2015</time>
						<h4><a href="#">Quisque varius ante lorem, eget pretium purus hendrerit a egestas. </a></h4>
						<time class="date" datetime="2015-02-02">February 2, 2015</time>
						<h4><a href="#">Phasellus in augue risus. </a></h4>
						<time class="date" datetime="2015-01-23">January 23, 2015</time>
						<div class="btn-holder">
							<a href="#" class="btn btn-link">Go to Blog</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<%= render 'layouts/footer' %>
	
</div>
<script src="js/jquery-1.11.2.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.main.js"></script>
</body>
</html>

app/views/employees/delete.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>EMPLOYEES/DELETE</h1>
</body>
</html>

app/views/employees/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>EMPLOYEES/EDIT</h1>
</body>
</html>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>softInstaller</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="styleeshet" href="images/favicon.ico">
	<link rel="stylesheet" href="/assets/bootstrap.css">
	<link rel="stylesheet" href="/assets/all.css">
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700|Source+Sans+Pro:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="wrapper">

	

	<div class = "container">
		<h2>Greetings, <%= current_employee.name %> <%= current_employee.surname %></h2>
		<button class="btn btn-success"><%= link_to "Log out", destroy_employee_session_path, :method => :delete %></button>
	</div>

	<%= render 'layouts/footer' %>
	
</div>
<script src="js/jquery-1.11.2.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.main.js"></script>
</body>
</html>

app/views/employees/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>EMPLOYEES/NEW</h1>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="footer-holder">
			<div class="row">
				<div class="col-md-4">
					<div class="logo"><a href="#"><img src="/images/beta-testing.jpg" width="100" height="100" alt="softInstaller"></a></div>
				</div>
				<div class="col-md-2">
					<h4>Navigation</h4>
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">Overview</a></li>
						<li><a href="#">About</a></li>
						<li><a href="#">Support</a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<div class="text-holder">
						<strong class="phone"><a href="tel:9999999999">999 999 99 99</a></strong>
						<span class="available">Available from 9AM - 18PM</span>
						<h4>California</h4>
						<address>*some address*</address>
					</div>
				</div>
				<div class="col-md-3">
					<div class="text-frame">
						<h4>Info</h4>
						<p>Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex commodo consequat. Autem vel hendrerit iriure dolor in hendrerit.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
	<div class="container">
		<div class="logo"><a href="#"><img src="/images/beta-testing.jpg" height="70" width="100" alt="softInstaller"></a></div>
		<nav id="nav">
			<div class="opener-holder">
				<a href="#" class="nav-opener"><span></span></a>
			</div>
			<div class="nav-drop">
				<ul>
					<li class="active visible-sm visible-xs"><a href="#">Home</a></li>
					<li><a href="#">Overview</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Support</a></li>
				</ul>
			</div>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Softinstaller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/delete.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>PROFILES/DELETE</h1>
</body>
</html>

app/views/profiles/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>PROFILES/EDIT</h1>
</body>
</html>

app/views/profiles/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<h1>PROFILES/NEW</h1>
</body>
</html>

app/views/software/delete.html.erb
<h1>Software#delete</h1>
<p>Find me in app/views/software/delete.html.erb</p>

app/views/software/edit.html.erb
<h1>Software#edit</h1>
<p>Find me in app/views/software/edit.html.erb</p>

app/views/software/new.html.erb
<h1>Software#new</h1>
<p>Find me in app/views/software/new.html.erb</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>softInstaller</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="styleeshet" href="images/favicon.ico">
	<link rel="stylesheet" href="/assets/bootstrap.css">
	<link rel="stylesheet" href="/assets/all.css">
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700|Source+Sans+Pro:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="wrapper">

	<%= render 'layouts/header' %>

	<section class="visual">
		<div class="container">
			<div class="text-block">
				<div class="heading-holder">
					<h1>softInstaller</h1>
				</div>
				<p class="tagline">Make your software installation process easier!</p>
			</div>
		</div>
		<img src="images/image_server.jpg" alt="" class="bg-stretch bg-img">
	</section>

	<section class="area">
		<div class="container">
			<div class="row">
				<div class="col-md-6">

					<ul class="visual-list">
						<li>
							<div class="img-holder">
								<img src="images/graph-01.svg" height="71" alt="">
							</div>
							<div class="text-holder">
								<h3>Designed to save your time</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
						<li>
							<div class="img-holder">
								<img src="images/graph-04.svg" width="110" alt="">
							</div>
							<div class="text-holder">
								<h3>Easy to use</h3>
								<p>Aenean cursus imperdiet nisl id fermentum. Aliquam pharetra dui laoreet vulputate dignissim. Sed id metus id quam auctor molestie eget ut augue. </p>
							</div>
						</li>
					</ul>
				</div>

				<div class="col-md-6">
					<ul class="visual-list">
						<li>
							<div class="img-holder">
								<img class="pull-left" src="images/graph-03.svg" width="90" alt="">
							</div>
							<div class="text-holder">
								<h3>High processing speed</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
						<li>
							<div class="img-holder">
								<img src="images/graph-02.svg" height="84" alt="">
							</div>
							<div class="text-holder">
								<h3>Experimental Features</h3>
								<p>Maecenas eu dictum felis, a dignissim nibh. Mauris rhoncus felis odio, ut volutpat massa placerat ac. Curabitur dapibus iaculis mi gravida luctus. Aliquam erat volutpat. </p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>

	<section class="area-socials">
		<div class="visual-area">
			<div class="container">
				<h2>Our socials</h2>
				<ul class="cta-list">
					<li>
						<a href="#" class="btn btn-info"><i class="fa fa-twitter"></i> Twitter</a>
					</li>
					<li>
						<a href="#" class="btn btn-blue"><i class="fa fa-facebook"></i> Facebook</a>
					</li>
				</ul>	
			</div>
		</div>
	</section>

	<section class="visual-container">
		<div class="visual-area">
			<div class="container">
				<h2>Subscription Pricing</h2>
				<div class="pricing-tables">

					<div class="plan">
		                <div class="head">
		                    <h3>Free</h3>
		                </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>0</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                <ul class="item-list">
		                    <li>30 GB Storage </li>
		                </ul>
		                <button type="button" class="btn btn-default rounded"><%= link_to "purchase", new_employee_registration_path %></button>
		            </div>

		            <div class="plan">
		                <div class="head">
		                    <h3>professional</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>4.99</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                    <ul class="item-list">
		                       <li>100 GB Storage</li>
		                       <li>Email Support</li>
		                    </ul>
		                <button type="button" class="btn btn-default rounded"><%= link_to "purchase", new_employee_registration_path %></button>
		            </div>
		            <div class="plan recommended">
		                <div class="head">
		                    <h3>agency</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>1000</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                    <ul class="item-list">
		                        <li>1 TB Storage</li>
		                        <li>Free hugs</li>
		                    </ul>
		                <button type="button" class="btn btn-default rounded"><%= link_to "purchase", new_employee_registration_path %></button>
		            </div>
		            <div class="plan">
		                <div class="head">
		                    <h3>company</h3> </div>
		                <div class="price">
		                    <span class="price-main"><span class="symbol">$</span>79</span>
		                    <span class="price-additional">per month</span>
		                </div>
		                <ul class="item-list">
		                    <li>Unlimited Storage</li>
		                    <li>Free pizza</li>
		                </ul>
		                <button type="button" class="btn btn-default rounded"><%= link_to "purchase", new_employee_registration_path %></button>
		            </div>
				</div>
			</div>
			<img src="../images/img-decor-01.jpg" height="1175" width="1380" alt="" class="bg-stretch bg-img">
		</div>
	</section>
	<section class="area">
		<div class="container">
			<div class="subscribe">
				<h3>Subscribe to Our Mail Delivery</h3>
				<form class="form-inline">
					<button type="submit" class="btn btn-primary rounded">Subscribe</button>
					<div class="form-group">
						<input type="email" class="form-control rounded" id="exampleInputEmail2" placeholder="Email...">
					</div>
				</form>
			</div>
		</div>
	</section>
	<section class="main">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="col-md-6">
						<h3>New in Release</h3>
						<h4>Cross-browser compatibility</h4>
						<p>Morbi faucibus ante ipsum, a tincidunt libero posuere et. Etiam tempor tortor at odio condimentum, sit amet fringilla ligula maximus. Mauris venenatis nisl nisi, et dictum dui aliquet nec. Sed erat, nec aliquam vel, aliquam ac felis. </p>
						<h4>Mail delivery service </h4>
						<p>Nulla purus quam, pulvinar sed ante et, feugiat maximus velit. Donec eu elit mauris. </p>
						<h4>New Design</h4>
						<p>Proin id ligula eget massa tincidunt molestie. Morbi urna lectus, molestie vel quam vel, iaculis fermentum nunc. Morbi imperdiet, leo in interdum pretium.</p>
						<div class="btn-holder">
							<a href="#" class="btn btn-link">Go to Release Log</a>
						</div>
					</div>
					<div class="col-md-6">
						<h3>New From the Blog</h3>
						<h4><a href="#">Morbi imperdiet, leo in interdum pretium.</a></h4>
						<time class="date" datetime="2015-02-18">February 18, 2015</time>
						<h4><a href="#">Donec orci ante, porta vel nulla quis, aliquet hendrerit leo.</a></h4>
						<time class="date" datetime="2015-02-12">February 12, 2015</time>
						<h4><a href="#">Suspendisse egestas vulputate luctus.</a></h4>
						<time class="date" datetime="2015-02-06">February 6, 2015</time>
						<h4><a href="#">Quisque varius ante lorem, eget pretium purus hendrerit a egestas. </a></h4>
						<time class="date" datetime="2015-02-02">February 2, 2015</time>
						<h4><a href="#">Phasellus in augue risus. </a></h4>
						<time class="date" datetime="2015-01-23">January 23, 2015</time>
						<div class="btn-holder">
							<a href="#" class="btn btn-link">Go to Blog</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<%= render 'layouts/footer' %>
	
</div>
<script src="js/jquery-1.11.2.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.main.js"></script>
</body>
</html>